version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppassword
      POSTGRES_DB: erpdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "2025:2025"
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=erpdb
      - DJANGO_DB_USER=erpuser
      - DJANGO_DB_PASSWORD=erppassword
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "2026:2026"
    environment:
      - REACT_APP_API_URL=http://localhost:2025/api
volumes:
  postgres_data:
