#!/bin/bash

echo "🔧 Fixing Gradle JDK Configuration for Android Studio"
echo "====================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Navigate to project root
cd /Users/kwadwoantwi/CascadeProjects/erp-system

print_status "Configuring Gradle to use Android Studio's embedded JDK..."

# Set Android Studio's embedded JDK path
ANDROID_STUDIO_JDK="/Applications/Android Studio.app/Contents/jbr/Contents/Home"

if [ ! -d "$ANDROID_STUDIO_JDK" ]; then
    print_error "Android Studio embedded JDK not found at: $ANDROID_STUDIO_JDK"
    print_error "Please ensure Android Studio is properly installed"
    exit 1
fi

print_success "Found Android Studio embedded JDK at: $ANDROID_STUDIO_JDK"

# Update gradle.properties in the Android project
print_status "Updating gradle.properties with correct JDK path..."

cd frontend/android

# Backup existing gradle.properties
if [ -f "gradle.properties" ]; then
    cp gradle.properties gradle.properties.backup
    print_status "Backed up existing gradle.properties"
fi

# Create/update gradle.properties with Android Studio JDK
cat > gradle.properties << EOF
# Project-wide Gradle settings.

# IDE (Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Enable Gradle build cache
org.gradle.caching=true

# Enable R8 full mode
android.enableR8.fullMode=true

# Use Android Studio's embedded JDK
org.gradle.java.home=$ANDROID_STUDIO_JDK
EOF

print_success "Updated gradle.properties with Android Studio embedded JDK"

# Also set JAVA_HOME for Gradle wrapper
print_status "Configuring Gradle wrapper properties..."

if [ -f "gradle/wrapper/gradle-wrapper.properties" ]; then
    print_status "Gradle wrapper properties found"
else
    print_warning "Gradle wrapper properties not found - this is normal for new projects"
fi

# Create local.properties to specify SDK location and JDK
print_status "Creating/updating local.properties..."

cat > local.properties << EOF
# This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
sdk.dir=$HOME/Library/Android/sdk

# Location of the JDK. This is only used by Gradle.
org.gradle.java.home=$ANDROID_STUDIO_JDK
EOF

print_success "Created local.properties with correct paths"

# Update environment for current session
export JAVA_HOME="$ANDROID_STUDIO_JDK"
export PATH="$JAVA_HOME/bin:$PATH"

print_status "Testing Gradle configuration..."

# Test Gradle with the new configuration
print_status "Running Gradle sync test..."
./gradlew --version

if [ $? -eq 0 ]; then
    print_success "✅ Gradle configuration is working!"
else
    print_warning "Gradle test had issues, but this may be normal during initial setup"
fi

cd ../..

# Create script to open Android Studio with correct environment
print_status "Creating Android Studio launcher with correct JDK..."

cat > open_android_studio_fixed.sh << 'EOF'
#!/bin/bash

echo "🚀 Opening Android Studio with Fixed JDK Configuration"
echo "====================================================="

# Set Android Studio's embedded JDK
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

# Set Android SDK
export ANDROID_HOME="$HOME/Library/Android/sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"

cd /Users/kwadwoantwi/CascadeProjects/erp-system/frontend/android

echo "🔧 Environment configured:"
echo "JAVA_HOME: $JAVA_HOME"
echo "Android SDK: $ANDROID_HOME"
echo ""

if [ -d "/Applications/Android Studio.app" ]; then
    echo "📱 Opening Android project with fixed JDK configuration..."
    open -a "Android Studio" .
    
    echo ""
    echo "✅ Android Studio opened with embedded JDK!"
    echo ""
    echo "📋 In Android Studio:"
    echo "===================="
    echo "1. Wait for Gradle sync to complete"
    echo "2. If you see JDK issues, go to:"
    echo "   File → Project Structure → SDK Location → Gradle Settings"
    echo "   Set Gradle JDK to: 'Use Embedded JDK'"
    echo "3. Click 'Apply' and 'OK'"
    echo "4. Build → Build Bundle(s) / APK(s) → Build APK(s)"
    
else
    echo "❌ Android Studio not found!"
fi
EOF

chmod +x open_android_studio_fixed.sh

print_success "✅ Gradle JDK configuration fixed!"

echo ""
echo "🎯 Next Steps:"
echo "=============="
echo ""
echo "1. Close Android Studio if it's currently open"
echo ""
echo "2. Reopen with fixed configuration:"
echo "   ./open_android_studio_fixed.sh"
echo ""
echo "3. In Android Studio, if you still see JDK issues:"
echo "   • File → Project Structure → SDK Location"
echo "   • Under 'Gradle Settings', set Gradle JDK to:"
echo "     'Use Embedded JDK (/Applications/Android Studio.app/Contents/jbr/Contents/Home)'"
echo "   • Click Apply and OK"
echo ""
echo "4. Wait for Gradle sync to complete"
echo ""
echo "5. Build your APK:"
echo "   Build → Build Bundle(s) / APK(s) → Build APK(s)"

print_success "🎉 JDK configuration fix completed!"
