# Generated by Django 5.2.4 on 2025-08-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_product_fields'),
        ('warehouse', '0002_stockmovement_product_warehousetransfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('max_stock_level', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='warehouse.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse', 'product'], name='warehouse_w_warehou_22076a_idx'), models.Index(fields=['quantity'], name='warehouse_w_quantit_c1812b_idx')],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
