# Generated by Django 5.2.4 on 2025-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehousestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='waybill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='waybills/'),
        ),
    ]
