# Generated by Django 5.2.4 on 2025-07-17 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('SLL', 'Sierra Leonean Leone'), ('USD', 'US Dollar'), ('LRD', 'Liberian Dollar'), ('GHS', 'Ghana Cedi')], default='SLL', max_length=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.possession')),
            ],
        ),
    ]
