# Generated by Django 5.2.4 on 2025-07-31 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_onboardingprocess_onboardingfeedback_onboardingstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General Announcement'), ('policy', 'Policy Update'), ('event', 'Event Announcement'), ('holiday', 'Holiday Notice'), ('deadline', 'Deadline Reminder'), ('training', 'Training Announcement'), ('emergency', 'Emergency Notice'), ('celebration', 'Celebration'), ('other', 'Other')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('audience_type', models.CharField(choices=[('all', 'All Employees'), ('department', 'Specific Department'), ('role', 'Specific Role'), ('custom', 'Custom Selection')], default='all', max_length=20)),
                ('publish_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ManyToManyField(related_name='read_announcements', through='hr.AnnouncementRead', to=settings.AUTH_USER_MODEL)),
                ('target_departments', models.ManyToManyField(blank=True, to='hr.department')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.enhancedannouncement'),
        ),
        migrations.CreateModel(
            name='HRCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('company_event', 'Company Event'), ('holiday', 'Holiday'), ('hr_deadline', 'HR Deadline'), ('training', 'Training Session'), ('meeting', 'Meeting'), ('birthday', 'Employee Birthday'), ('anniversary', 'Work Anniversary'), ('leave', 'Employee Leave'), ('recruitment', 'Recruitment Event'), ('performance_review', 'Performance Review'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all employees')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('send_notifications', models.BooleanField(default=True)),
                ('notification_days_before', models.PositiveIntegerField(default=1, help_text='Days before event to send notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this event applies to', to='hr.department')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HRCalendarNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr.hrcalendarevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='HRDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline_type', models.CharField(choices=[('performance_review', 'Performance Review'), ('training_completion', 'Training Completion'), ('document_submission', 'Document Submission'), ('compliance', 'Compliance Deadline'), ('recruitment', 'Recruitment Deadline'), ('payroll', 'Payroll Deadline'), ('benefits', 'Benefits Deadline'), ('audit', 'Audit Deadline'), ('other', 'Other')], default='other', max_length=20)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=3, help_text='Days before deadline to send reminders')),
                ('send_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(related_name='hr_deadlines', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deadlines', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
            ],
            options={
                'ordering': ['due_date', 'due_time'],
            },
        ),
        migrations.CreateModel(
            name='HRHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('company', 'Company Holiday'), ('religious', 'Religious Holiday'), ('cultural', 'Cultural Holiday'), ('observance', 'Observance')], default='company', max_length=20)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_work_day', models.BooleanField(default=False, help_text='Whether employees are expected to work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this holiday applies to', to='hr.department')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together={('announcement', 'user')},
        ),
    ]
