# Generated by Django 5.2.4 on 2025-07-31 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_announcementread_enhancedannouncement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('compassionate', 'Compassionate Leave'), ('study', 'Study Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('total_days', models.PositiveIntegerField(default=0, help_text='Total leave days allocated for the year')),
                ('used_days', models.PositiveIntegerField(default=0, help_text='Leave days already used')),
                ('pending_days', models.PositiveIntegerField(default=0, help_text='Leave days in pending requests')),
                ('year', models.PositiveIntegerField(help_text='Year this balance applies to')),
                ('carry_over_days', models.PositiveIntegerField(default=0, help_text='Days carried over from previous year')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
