# Generated by Django 5.2.4 on 2025-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('retailer', 'Retailer')], default='retailer', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.PositiveIntegerField(default=30, help_text='Days allowed for payment (e.g. 30, 60, 120)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('SLL', 'Sierra Leonean Leone'), ('USD', 'US Dollar'), ('LRD', 'Liberian Dollar'), ('GHS', 'Ghana Cedi')], default='SLL', max_length=3),
        ),
    ]
