# Generated by Django 5.2.4 on 2025-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customerapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS Latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS Longitude', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='customerapproval',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS Latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerapproval',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='customerapproval',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AddField(
            model_name='customerapproval',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS Longitude', max_digits=11, null=True),
        ),
    ]
