# Generated by Django 5.2.4 on 2025-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_lead_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
