# Generated by Django 5.2.4 on 2025-08-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0007_promotion_promotionproduct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotionproduct',
            name='unique_promotion_product',
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together={('promotion', 'product')},
        ),
    ]
