# Generated by Django 5.2.4 on 2025-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_customer_latitude_alter_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerapproval',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerapproval',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=10, null=True),
        ),
    ]
