# Generated by Django 5.2.4 on 2025-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS Latitude', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customerapproval',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS Latitude', max_digits=5, null=True),
        ),
    ]
