# Generated by Django 5.2.4 on 2025-08-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
        migrations.AlterField(
            model_name='customerapproval',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='customerapproval',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
    ]
