# Generated by Django 5.2.4 on 2025-07-31 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='procurementaudit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='procurementrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='approval_stage',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='stage',
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='assigned_finance_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_finance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='assigned_procurement_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_procurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='bid_analysis_report',
            field=models.FileField(blank=True, null=True, upload_to='procurement/bid_analysis/'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_proc_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='current_stage',
            field=models.CharField(choices=[('requester', 'Requester'), ('hod', 'HOD'), ('cd', 'Country Director'), ('procurement_manager', 'Procurement Manager'), ('procurement_officer', 'Procurement Officer'), ('finance_manager', 'Finance Manager'), ('finance_officer', 'Finance Officer'), ('final_approval', 'Final Approval'), ('completed', 'Completed')], default='requester', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_voucher_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='po_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='po_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='po_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowinstance'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proc_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='BidAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_quotes', models.JSONField(default=dict)),
                ('analysis_notes', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procurement_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_analysis', to='procurement.procurementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('requester', 'Requester'), ('hod', 'HOD'), ('cd', 'Country Director'), ('procurement_manager', 'Procurement Manager'), ('procurement_officer', 'Procurement Officer'), ('finance_manager', 'Finance Manager'), ('finance_officer', 'Finance Officer'), ('final_approval', 'Final Approval'), ('completed', 'Completed')], max_length=30)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.procurementrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procurement_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='procurement.procurementrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('approved_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_vouchers', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_voucher', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
    ]
