# Generated by Django 5.2.4 on 2025-08-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_add_approval_stages'),
        ('procurement', '0002_vendor_alter_procurementaudit_options_and_more'),
    ]

    operations = [
    ]
