# Generated by Django 5.2.4 on 2025-08-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_merge_20250816_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='approval_stage',
            field=models.CharField(
                choices=[
                    ('submitted', 'Submitted'),
                    ('dept', 'Department Review'),
                    ('procurement', 'Procurement Review'),
                    ('finance', 'Finance Review'),
                    ('complete', 'Complete')
                ],
                default='submitted',
                max_length=20
            ),
        ),
    ]
