# Generated by Django 5.2.4 on 2025-08-16 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_approval_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='approval_stage',
            field=models.CharField(choices=[('dept', 'Department'), ('procurement', 'Procurement'), ('finance', 'Finance'), ('complete', 'Complete')], default='dept', max_length=30),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
