# Generated by Django 5.2.4 on 2025-08-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_approval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='approval_stage',
            field=models.CharField(
                choices=[
                    ('requester', 'Requester'),
                    ('hod', 'HOD'),
                    ('cd', 'Country Director'),
                    ('procurement_manager', 'Procurement Manager'),
                    ('procurement_officer', 'Procurement Officer'),
                    ('finance_manager', 'Finance Manager'),
                    ('finance_officer', 'Finance Officer'),
                    ('final_approval', 'Final Approval'),
                ],
                default='requester',
                max_length=30
            ),
        ),
    ]
