# Generated by Django 5.2.4 on 2025-08-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_procurementrequest_approval_stage_and_more'),
        ('procurement', '0005_update_approval_stages_to_8_stage'),
    ]

    operations = [
    ]
