# Generated by Django 5.2.4 on 2025-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_merge_20250816_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='approver',
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='approval_stage',
            field=models.CharField(choices=[('requester', 'Requester'), ('hod', 'HOD'), ('cd', 'Country Director'), ('procurement_manager', 'Procurement Manager'), ('procurement_officer', 'Procurement Officer'), ('finance_manager', 'Finance Manager'), ('finance_officer', 'Finance Officer'), ('final_approval', 'Final Approval')], default='requester', max_length=30),
        ),
    ]
