# Generated by Django 5.2.4 on 2025-07-28 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('pos', 'Point of Sale'), ('warehouse', 'Warehouse'), ('customers', 'Customers'), ('reporting', 'Reporting')], max_length=20)),
                ('target_module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('pos', 'Point of Sale'), ('warehouse', 'Warehouse'), ('customers', 'Customers'), ('reporting', 'Reporting')], max_length=20)),
                ('integration_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'module_integrations',
                'unique_together': {('source_module', 'target_module', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('SALES_ORDER_CREATED', 'Sales Order Created'), ('PURCHASE_ORDER_CREATED', 'Purchase Order Created'), ('PRODUCTION_ORDER_CREATED', 'Production Order Created'), ('INVENTORY_MOVEMENT', 'Inventory Movement'), ('WAREHOUSE_TRANSFER', 'Warehouse Transfer'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('POS_SALE_COMPLETED', 'POS Sale Completed'), ('CUSTOMER_CREATED', 'Customer Created'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('MATERIAL_REQUEST', 'Material Request'), ('QUALITY_CHECK', 'Quality Check'), ('SHIPMENT_CREATED', 'Shipment Created'), ('RETURN_PROCESSED', 'Return Processed')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('source_module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('pos', 'Point of Sale'), ('warehouse', 'Warehouse'), ('customers', 'Customers'), ('reporting', 'Reporting')], db_index=True, max_length=20)),
                ('target_modules', models.JSONField(default=list)),
                ('transaction_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('workflow_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('workflow_step', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('pos', 'Point of Sale'), ('warehouse', 'Warehouse'), ('customers', 'Customers'), ('reporting', 'Reporting')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('incoming_transactions', models.IntegerField(default=0)),
                ('outgoing_transactions', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_processing_time', models.DurationField(blank=True, null=True)),
                ('top_sources', models.JSONField(default=list)),
                ('top_targets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_analytics',
                'ordering': ['-date'],
                'unique_together': {('module', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_module', 'created_at'], name='transaction_source__63350b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['workflow_id', 'workflow_step'], name='transaction_workflo_b5999d_idx'),
        ),
    ]
