# Generated by Django 5.2.4 on 2025-07-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of modules this user can access'),
        ),
    ]
