# Generated by Django 5.2.4 on 2025-07-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_accessible_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_module_restricted',
            field=models.BooleanField(default=False, help_text='Whether this user has module access restrictions'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_module_update',
            field=models.DateTimeField(auto_now=True, help_text='Last time module permissions were updated'),
        ),
    ]
