# Generated by Django 5.2.4 on 2025-07-29 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_module_restricted_user_last_module_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ERP System', max_length=100)),
                ('site_description', models.TextField(default='Enterprise Resource Planning System')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('default_user_role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('accountant', 'Accountant'), ('sales', 'Salesperson'), ('cashier', 'POS Cashier')], default='employee', max_length=20)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('password_min_length', models.IntegerField(default=8)),
                ('require_password_complexity', models.BooleanField(default=True)),
                ('enable_two_factor', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(default='daily', max_length=20)),
                ('log_retention_days', models.IntegerField(default=90)),
                ('smtp_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_from_name', models.CharField(default='ERP System', max_length=100)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('user_registration_notifications', models.BooleanField(default=True)),
                ('password_reset_notifications', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('maintenance_notices', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('daily_reports', models.BooleanField(default=False)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('monthly_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
