# Generated by Django 5.2.4 on 2025-07-30 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_table_systemsettings'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse assigned to this user (for Sales Reps)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='warehouse.warehouse'),
        ),
    ]
